# config
cover: /img/bk1920x657.jpg
logo: /img/panda.png
top_saying:
#- title: YOU'VE MADE A <span>BRAVE</span> DECISION, WELCOME.
#- content: 每一个不曾起舞的日子都是对生命的辜负。
#bottom_saying: 虽然还没想好写点什么，但是总觉得这里放句话比较和谐。
- title: #HERE YOU ARE
- content:
#bottom_saying: - - -
# Content
excerpt_link: Read More

rss: /atom.xml

highlightjs: vs

#Works
works:
- works_name: AAA
  works_url: /
- works_name: BBB
  works_url: /atom.xml

#duoshuo name
duoshuo:

#disqus name
disqus_shortname:

#fancybox
fancybox: true

# Miscellaneous
github: https://github.com/luppiterw
#twitter: https://twitter.com/
#facebook: https://www.facebook.com/
#google: https://google.com/
weibo: http://weibo.com/whlittlep

#about  timeline
timeline:
- num: 1
  word: 2019/12/22-开启0x0000随笔博客
- num: 2
  word: 2020/12/31-2020的最后一天
- num: 3
  word: 2024/06/11-迁移至GitLab/GitHub
- num: 4
  word: 持续记录中...

#Links
links:
- name: Hughie
  link: http://hughie.me/
- name: Name
  link: http://hughie.me/